### ISSUE TITLE
Remove me from this repo

### ISSUE THREAD

**Issue by BurntCaramel** [hooroo/url_scrambler#3]
@KamalMicheal

**Comment by KamalMicheal** [comment]
Hey mate @BurntCaramel 
I was wondering if "unwatch" could do it :)

**Comment by BurntCaramel** [comment]
It already says Not Watching
<img width="347" alt="image" src="https://user-images.githubusercontent.com/2635733/81377788-88ae8400-9149-11ea-86eb-6bad5fdcc9b5.png">
